# Complete list of all available properties: https://docs.upsun.com/create-apps/app-reference.html
applications:
  url-shortener-golang:
    source:
      root: "/"

    type: "golang:1.23"

    container_profile: HIGH_CPU

    relationships:
      postgresql:

    web:
      commands:
        start: "./$BINARY"

      upstream:
        socket_family: tcp
        protocol: http

      locations:
        "/":
          allow: false
          passthru: true

    timezone: Asia/Kolkata

    variables:
      env:
        BINARY: "bin/urlshortener"

    build:
      flavor: none

    hooks:
      build: |
        set -eux

        go mod download
        go build -o $BINARY

services:
  postgresql:
    type: postgresql:16
    container_profile: HIGH_MEMORY

routes:
  "https://l.{default}/":
    type: upstream
    upstream: "url-shortener-golang:http"
